import Head from "next/head";
import Link from "next/link";
import { CookieHandler } from "~/utils/cookie_handler";
import { api } from "~/utils/api";
import { useEffect,useState } from "react"
import Cookies from "js-cookie"
export default function Home() {
  const [username,set_username] = useState("")
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const cookie_handler = new CookieHandler;
  useEffect(() => {
      set_username(JSON.parse(Cookies.get('user')))
  }, [])
  
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <h1>HI { username.username}</h1>
      </main>
    </>
  );
}
