import Head from "next/head";
import Link from "next/link";
import { CookieHandler } from "~/utils/cookie_handler";
import { api } from "~/utils/api";
import { useEffect, useState } from "react"
import Cookies from "js-cookie"
import {User} from "~/utils/types"
export default function Home() {
  const [user,set_user] = useState()
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const cookie_handler = new CookieHandler;
  useEffect(() => {
    const cookie: string | boolean = cookie_handler.checkForCookie('user') 
    if (!cookie) {
      window.location.href = '/login';
      return;
    }
    const user:User = JSON.parse(cookie) 
      set_user(user)

    //---------------------

    
  }, [])
  
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        {user ? <h1>HI { user.username}</h1> : <div>Loading data</div>}
      </main>
    </>
  );
}
