import Head from "next/head";
import Link from "next/link";
import { CookieHandler } from "~/utils/cookie_handler";
import { api } from "~/utils/api";
import { useEffect, useState } from "react"
import Cookies from "js-cookie"
import {User} from "~/utils/types"
import {application_url} from "./constant_variables/constants"
interface ExercisesProps {
  has_program: boolean;
}

interface Program{
  data:object
}

function Exercises({ has_program }: ExercisesProps) {
  return (
    <div>
      {has_program ? (
        <>
          {/* Add your content here for when has_program is true */}
          hi
        </>
      ) : (
        <>
          <div>
            {/* Add your content here for when has_program is false */}
            <Link href={`${application_url}/add_program`}>create program</Link>
            no program
          </div>
        </>
      )}
    </div>
  );
}






export default function Home() {
  const [user, set_user] = useState()
  const program:Program = api.post.get_exercises.useQuery(user ? { username: user.username,token:user.token } : {username:""}) 
  const cookie_handler = new CookieHandler;
  useEffect(() => {
    const cookie: string | boolean = cookie_handler.checkForCookie('user') 
    if (!cookie) {
      window.location.href = '/login';
      return;
    }
    const user: User = typeof (cookie) === 'string' ? JSON.parse(cookie) : undefined; 
    set_user(user)

    //---------------------
    console.log(program)

  }, [])
  
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        {user ? <h1>HI { user.username}</h1> : <div>Loading data</div>}
        <Exercises has_program={program.data ?(program.data.error ? false : true): false } />
      </main>
    </>
  );
}
