version: '24.0.6'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"

  express-server:
    build: .
    container_name: express-server-container
    ports:
      - "3008:3008"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: my-secret-pw
      DB_DATABASE: mydatabase