version: '24.0.6'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"

  
  notification_service:
    build:
      context: C:\Users\Hrisi\Desktop\Gym_progress_tracker\gym\notification_service
      dockerfile: dockerfile
    image: notification_service
    ports:
    - "3008:3008"

  auth_service:
    build:
      context: C:\Users\Hrisi\Desktop\Gym_progress_tracker\gym\auth_service
      dockerfile: dockerfile
    image: auth_service
    ports:
    - "3000:3000" 

  gateway:
    build:
      context: C:\Users\Hrisi\Desktop\Gym_progress_tracker\gym\gateway
      dockerfile: dockerfile
    image: gateway
    ports:
    - "3002:3002"


  exercises_service:
    build:
      context: C:\Users\Hrisi\Desktop\Gym_progress_tracker\gym\exercises_service
      dockerfile: dockerfile
    image: exercises_service
    ports:
    - "3007:3007"
