FROM node:latest

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

RUN npm install -g prisma

COPY ./prisma ./prisma

RUN npx prisma migrate deploy

RUN npx prisma generate

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
